apiVersion: v1
kind: PersistentVolume
metadata:
 name: mongo-pv
 namespace: graylog
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: 5Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/mongo_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mongo-pv-claim
 namespace: graylog
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: graylog
  labels:
    service: mongo
spec:
  replicas: 1
  serviceName: "mongo"
  selector:
    matchLabels: 
      service: mongo
  template:
    metadata:
      labels:
        service: mongo
    spec:      
      containers:
      - name: mongodb
        image: mongo:3
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongo-pv-storage
          mountPath: /data/db
      volumes:
      - name: mongo-pv-storage
        persistentVolumeClaim:
         claimName: mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: graylog
spec:
  selector:
    service: mongo
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
        

